Repository mash-up-kr/mashup_Android, pull requests merged in 2022-12, with the labels that each got.

#150 Lint Check CI
  .github/workflows/lint_check.yml
Labels: 기능

#167 🛠 webview -> compose webview migration
  app/build.gradle
  app/src/main/java/com/mashup/ui/webview/WebViewActivity.kt
  app/src/main/res/layout/activity_web_view.xml
  dependencies.gradle
Labels: 리팩토링

#169 [Feature] SettingScreen SNS 이동 로직 변경
  app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
  app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
  app/src/main/java/com/mashup/ui/setting/sns/SNSListScreen.kt
Labels: 리팩토링, 기능

#170 [Bug] Typograpy 설정해둔 것들 자간(letterSpacing) 수정
  core/ui/src/main/java/com/mashup/core/ui/typography/Typography.kt
Labels: 리팩토링
