Repository mash-up-kr/mashup_Android, pull requests merged in 2023-02, with the labels that each got.

#221 🐛 포커스 줘서 키보드 올리기
  app/src/main/AndroidManifest.xml
  core/common/src/main/java/com/mashup/core/common/widget/TextFieldView.kt
Labels: 버그

#218 [Feature] 비밀번호 정규식 조건에 특수문자 추가(@$!%^#*?&) 및 가이드 문구 수정
  app/src/main/java/com/mashup/ui/signup/SignUpValidation.kt
  app/src/main/res/layout/fragment_sign_up_auth.xml
Labels: UI, 기능

#219 [Feature] ID 정규식 수정
  app/src/main/java/com/mashup/ui/signup/SignUpValidation.kt
  app/src/main/java/com/mashup/ui/signup/fragment/auth/SignUpAuthFragment.kt
  app/src/main/res/values/strings.xml
Labels: 기능

#211 [Feature] SettingScreen Compose UI Test
  .gitignore
  app/build.gradle
  app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
  app/src/main/res/values/strings.xml
  core/ui/src/main/java/com/mashup/core/ui/extenstions/shadow.kt
  core/ui/src/main/java/com/mashup/core/ui/widget/MashUpSwitch.kt
  feature/setting/.gitignore
  feature/setting/build.gradle
  feature/setting/consumer-rules.pro
  feature/setting/proguard-rules.pro
  feature/setting/src/androidTest/java/com/mashup/feature/SettingScreenTest.kt
  feature/setting/src/main/AndroidManifest.xml
  feature/setting/src/main/java/com/mashup/feature/SettingScreen.kt
  feature/setting/src/main/java/com/mashup/feature/constant/SNSUrl.kt
  feature/setting/src/main/java/com/mashup/feature/menu/SettingMenuItem.kt
  feature/setting/src/main/java/com/mashup/feature/menu/SettingMenuList.kt
  feature/setting/src/main/java/com/mashup/feature/model/SNSModel.kt
  feature/setting/src/main/java/com/mashup/feature/sns/SNSItem.kt
  feature/setting/src/main/java/com/mashup/feature/sns/SNSList.kt
  feature/setting/src/main/res/values/strings.xml
  settings.gradle
Labels: UI, 기능

#213 [Fix] Spotless 미적용 부분 적용하기
  app/src/main/java/com/mashup/constant/log/UserActionKeys.kt
  app/src/main/java/com/mashup/constant/log/UserActionLogs.kt
  app/src/main/java/com/mashup/data/repository/FirebaseRepository.kt
  app/src/main/java/com/mashup/data/repository/MemberRepository.kt
  app/src/main/java/com/mashup/network/dao/MemberDao.kt
  app/src/main/java/com/mashup/ui/login/LoginType.kt
  app/src/main/java/com/mashup/ui/model/SNSModel.kt
  app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
  app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
  app/src/main/java/com/mashup/ui/webview/WebViewActivity.kt
  app/src/main/java/com/mashup/ui/widget/MashUpButton.kt
  app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt
  core/datastore/src/main/java/com/mashup/datastore/data/repository/AppPreferenceRepository.kt
  core/datastore/src/main/java/com/mashup/datastore/data/repository/UserPreferenceRepository.kt
  core/datastore/src/main/java/com/mashup/datastore/data/source/AppPreferenceSerializer.kt
  core/datastore/src/main/java/com/mashup/datastore/data/source/UserPreferenceSerializer.kt
  core/datastore/src/main/java/com/mashup/datastore/di/DataStoreModule.kt
  core/model/src/main/java/com/mashup/core/model/data/local/AppPreference.kt
  core/model/src/main/java/com/mashup/core/model/data/local/UserPreference.kt
  core/ui/src/main/java/com/mashup/core/ui/widget/MashUpSwitch.kt
  feature/setting/src/main/java/com/mashup/feature/menu/SettingMenuItem.kt
  feature/setting/src/main/java/com/mashup/feature/menu/SettingMenuList.kt
Labels: 리팩토링

#240 [Bug] 플랫폼 출결 현황 "일정 시작 전 문구 표시"
  app/build.gradle
  app/src/main/java/com/mashup/ui/attendance/platform/PlatformAttendanceViewModel.kt
  app/src/test/java/com/mashup/PlatformAttendanceViewModelTest.kt
  app/src/test/java/com/mashup/fake/FakeAttendanceDao.kt
  app/src/test/java/com/mashup/util/CoroutineRule.kt
Labels: 버그, UI

#247 [Refactoring] PlatformAttendanceViewModelTest 중복코드 정리
  app/src/test/java/com/mashup/PlatformAttendanceViewModelTest.kt
Labels: 리팩토링
