Repository mash-up-kr/mashup_Android, pull requests merged in 2023-04, with the labels that each got.

#269 [Feature] Shake Detector 기능 구현 Step - 1
  app/src/main/java/com/mashup/base/BaseActivity.kt
  app/src/main/java/com/mashup/base/BaseFragment.kt
  app/src/main/java/com/mashup/network/interceptor/AuthInterceptor.kt
  app/src/main/java/com/mashup/ui/attendance/crew/CrewAttendanceActivity.kt
  app/src/main/java/com/mashup/ui/attendance/crew/CrewAttendanceViewModel.kt
  app/src/main/java/com/mashup/ui/attendance/platform/PlatformAttendanceActivity.kt
  app/src/main/java/com/mashup/ui/attendance/platform/PlatformAttendanceViewModel.kt
  app/src/main/java/com/mashup/ui/login/LoginActivity.kt
  app/src/main/java/com/mashup/ui/login/LoginViewModel.kt
  app/src/main/java/com/mashup/ui/main/MainViewModel.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
  app/src/main/java/com/mashup/ui/qrscan/QRScanViewModel.kt
  app/src/main/java/com/mashup/ui/schedule/ScheduleViewModel.kt
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailActivity.kt
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailViewModel.kt
  app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
  app/src/main/java/com/mashup/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/mashup/ui/signup/fragment/SignUpCodeFragment.kt
  app/src/main/java/com/mashup/ui/signup/fragment/auth/SignUpAuthFragment.kt
  app/src/main/java/com/mashup/ui/signup/fragment/auth/SignUpAuthViewModel.kt
  app/src/main/java/com/mashup/ui/webview/WebViewViewModel.kt
  app/src/main/java/com/mashup/ui/withdrawl/WithdrawalViewModel.kt
  core/common/src/main/java/com/mashup/core/common/base/BaseViewModel.kt
  core/common/src/main/java/com/mashup/core/common/constant/AttendanceCode.kt
  core/common/src/main/java/com/mashup/core/common/constant/BaseCode.kt
  core/common/src/main/java/com/mashup/core/common/constant/MemberCode.kt
  core/common/src/main/java/com/mashup/core/common/constant/ScheduleCode.kt
  core/shake/.gitignore
  core/shake/build.gradle
  core/shake/consumer-rules.pro
  core/shake/proguard-rules.pro
  core/shake/src/main/AndroidManifest.xml
  core/shake/src/main/java/com/mashup/core/shake/ShakeDetector.kt
  core/shake/src/main/java/com/mashup/core/shake/di/SensorModule.kt
  feature/danggn/.gitignore
  feature/danggn/build.gradle
  feature/danggn/src/main/AndroidManifest.xml
  feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnViewModel.kt
  settings.gradle
Labels: 기능

#279 [Feature] 메인 화면에 당근 흔들기 화면으로 진입하는 버튼 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
  app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
  app/src/main/res/layout/activity_shake_danggn.xml
  app/src/main/res/layout/fragment_schedule.xml
  core/common/src/main/res/drawable/img_carrot_button.png
Labels: UI

#283 [Feature] 당근 흔들기(DanggnShakeContent), 당근 랭킹(DanggnRankingContent) 컴포저블 각각 생성
  app/build.gradle
  app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
  core/ui/src/main/java/com/mashup/core/ui/widget/MashupToolbar.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeContent.kt
  feature/setting/src/androidTest/java/com/mashup/feature/SettingScreenTest.kt
Labels: UI, 기능

#298 [Feature] 오늘의 랜덤 하소연(메시지) 기능 추가
  feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnViewModel.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/DanggnDao.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRandomTodayMessageResponse.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeContent.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/shake/RandomTodayMessage.kt
Labels: UI, 기능

#300 [feature] ranking ui viewModel 연결
  app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
  app/src/test/java/com/mashup/PlatformAttendanceViewModelTest.kt
  app/src/test/java/com/mashup/fake/FakeDanggnDao.kt
  app/src/test/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModelTest.kt
  app/src/test/java/com/mashup/util/CoroutineRule.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
Labels: 기능

#303 [feature] 등수별 컬러 추가 및 디바이더 추가 - STEP [1]
  core/common/src/main/res/font/gilroy_extrabold.otf
  core/common/src/main/res/font/gilroy_light.otf
  core/ui/src/main/java/com/mashup/core/ui/colors/LinearGradientColor.kt
  core/ui/src/main/java/com/mashup/core/ui/typography/Gilroy.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
Labels: UI

#306 [feature] 버튼 클릭시 최상단 이동 및 텍스트 추가, 매시업 버튼 위치 수정 - STEP[2]
  core/ui/src/main/java/com/mashup/core/ui/widget/MashUpButton.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
Labels: 리팩토링, UI

#308 [feature] 마이 랭킹 추가 및 아무도 흔들지 않았을 때 텍스트 추가
  core/common/src/main/java/com/mashup/core/common/utils/DecimalUtil.kt
  core/ui/src/main/java/com/mashup/core/ui/colors/BrandColor.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
Labels: UI, 기능
