Repository mash-up-kr/mashup_Android, pull requests merged in 2023-05, with the labels that each got.

#321 [Feature] 당근 흔들기 화면 일반 모드일 때와 황금 당근이 등장했을 때 UI 구분
  core/common/src/main/res/drawable/img_carrot.png
  core/common/src/main/res/drawable/img_fever_danggn.png
  core/common/src/main/res/drawable/img_fevertime_countdown_1.png
  core/common/src/main/res/drawable/img_fevertime_countdown_2.png
  core/common/src/main/res/drawable/img_fevertime_countdown_3.png
  core/common/src/main/res/drawable/img_fevertime_title.png
  feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnViewModel.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnGameController.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnModeController.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeContent.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeEffect.kt
Labels: UI, 기능

#325 [Feature] 당근 흔들 때 Effect 효과
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnModeController.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeEffect.kt
Labels: UI, 기능

#330 [feature] 플리퍼 추가 (network, layout, logging)
  app/build.gradle
  app/src/main/java/com/mashup/MashUpApplication.kt
  app/src/main/java/com/mashup/di/NetworkModule.kt
  core/network/src/main/java/com/mashup/network/Response2.kt
  dependencies.gradle
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/DanggnDao.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
Labels: 기능

#371 [Fix] 푸시알림 토글 동작 수정
  app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
Labels: 버그
