Repository mash-up-kr/mashup_Android, pull requests merged in 2023-06, with the labels that each got.

#389 [feature] 암호화 기능 추가
  .github/workflows/android.yml
  app/build.gradle
  app/src/main/java/com/mashup/network/interceptor/BaseInterceptor.kt
Labels: 기능

#385 [Feature] 피버 타임 카운트다운 리팩토링
  feature/danggn/src/main/java/com/mashup/feature/danggn/DanggnViewModel.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnGameController.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnMode.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/danggn/DanggnModeController.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/shake/DanggnShakeEffect.kt
Labels: 리팩토링

#401 [feat] API 연동
  app/src/test/java/com/mashup/fake/FakeDanggnDao.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/DanggnDao.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRankingMultipleRoundCheckResponse.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/dto/DanggnRankingSingleRoundCheckResponse.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/data/repository/DanggnRepository.kt
Labels: 기능

#396 [Feature] 당근 흔들기 업데이트 설명 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mashup/ui/danggn/DanggnUpdateActivity.kt
  app/src/main/java/com/mashup/ui/main/MainActivity.kt
  core/common/src/main/java/com/mashup/core/common/model/ActivityEnterType.kt
  core/ui/src/main/java/com/mashup/core/ui/widget/MashupToolbar.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ui/DanggnUpdateScreen.kt
  feature/danggn/src/main/res/values/strings.xml
Labels: UI, 기능

#400 [Feature] Danggn Update 문구
  .github/pull_request_template.md
  app/src/main/java/com/mashup/ui/main/MainActivity.kt
  app/src/main/java/com/mashup/ui/main/model/MainPopupType.kt
  core/ui/src/main/res/raw/keep.xml
Labels: UI

#397 [Feature] common dependencies 버전 업
  app/build.gradle
  app/src/main/java/com/mashup/service/MashUpFirebaseMessagingService.kt
  app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
  build.gradle
  core/common/build.gradle
  core/datastore/build.gradle
  core/model/build.gradle
  core/network/build.gradle
  core/testing/build.gradle
  core/ui/build.gradle
  dependencies.gradle
  feature/danggn/build.gradle
  feature/setting/build.gradle
Labels: 리팩토링

#412 [feat] lazy column으로 변경 + 매시업 전체 인원 보여주기 (11명 이상)
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
Labels: 리팩토링, UI, 기능

#414 [feat] viewModel 데이터 연동
  app/src/main/java/com/mashup/ui/danggn/ShakeDanggnActivity.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ShakeDanggnScreen.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnWeeklyRankingContent.kt
Labels: 리팩토링, UI, 기능

#417 [Feature] 리워드로 공지 등록하는 플로우 및 UI 개발
  app/src/main/res/values-v26/themes.xml
  app/src/main/res/values-v27/themes.xml
  app/src/main/res/values/themes.xml
  feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnFirstPlaceBottomPopup.kt
  feature/danggn/src/main/java/com/mashup/feature/danggn/reward/DanggnRewardPopup.kt
Labels: UI
