Repository mash-up-kr/mashup_Android, pull requests merged in 2023-10, with the labels that each got.

#458 [Refactoring]: 내 맘대로 Attendance 코드 정리
  app/src/main/java/com/mashup/ui/model/AttendanceModel.kt
  app/src/main/java/com/mashup/ui/mypage/AttendanceListAdapter.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageAdapterType.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageBaseViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListItemViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListLevelViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListNoneViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageScoreViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageTitleViewHolder.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage_attendance_history_level.xml
  app/src/main/res/layout/item_mypage_attendance_history_list.xml
  app/src/main/res/layout/item_mypage_attendance_score.xml
  app/src/main/res/layout/item_mypage_attendance_title.xml
  core/common/src/main/res/values/styles.xml
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/MyPageProfileEditViewModel.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/MyProfileRepository.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/edit/MyPageEditProfileScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/model/ProfileData.kt
Labels: 리팩토링, UI

#452 [Feature] 마이 페이지 API 연동
  app/build.gradle
  app/src/main/java/com/mashup/ui/danggn/DanggnInfoActivity.kt
  app/src/main/java/com/mashup/ui/model/AttendanceModel.kt
  app/src/main/java/com/mashup/ui/mypage/AttendanceListAdapter.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageAdapterType.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageBaseViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListItemViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListLevelViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListNoneViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageScoreViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageTitleViewHolder.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage_attendance_history_level.xml
  app/src/main/res/layout/item_mypage_attendance_history_list.xml
  app/src/main/res/layout/item_mypage_attendance_score.xml
  app/src/main/res/layout/item_mypage_attendance_title.xml
  core/common/src/main/res/values/styles.xml
  feature/danggn/build.gradle
  feature/myPage/build.gradle
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/MyPageProfileEditViewModel.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/MemberGenerationDao.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/MyProfileDao.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/MyProfileRepository.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/dto/MemberGenerationRequest.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/dto/MemberGenerationsResponse.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/dto/MemberProfileRequest.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/dto/MemberProfileResponse.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/dto/ValidResponse.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/di/NetworkModule.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/edit/MyPageEditCardScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/edit/MyPageEditProfileScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/model/ProfileData.kt
Labels: 리팩토링, 기능

#462 Feature/459/mypage profile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mashup/ui/danggn/DanggnInfoActivity.kt
  app/src/main/java/com/mashup/ui/mypage/AttendanceListAdapter.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileEditActivity.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageProfileViewHolder.kt
  app/src/main/res/layout/activity_my_profile_edit.xml
  app/src/main/res/layout/item_mypage_profile.xml
  core/common/src/main/res/drawable/ic_link.xml
  core/common/src/main/res/drawable/img_cake.xml
Labels: UI, 기능

#463 Feature/461/mypage profile card
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mashup/ui/main/MainActivity.kt
  app/src/main/java/com/mashup/ui/model/AttendanceModel.kt
  app/src/main/java/com/mashup/ui/mypage/AttendanceListAdapter.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageAdapterType.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileCardEditActivity.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageBaseViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListItemViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListLevelViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageListNoneViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageProfileCardViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageProfileViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageScoreViewHolder.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageTitleViewHolder.kt
  app/src/main/res/layout/activity_my_profile_card_edit.xml
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/card/MyPageProfileCardScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/card/ProfileCard.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/card/ProfileCardDetailScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/model/ProfileCardData.kt
Labels: UI, 기능

#466 Feature: 마이프로필 정보 링크 연결
  app/src/main/java/com/mashup/ui/mypage/AttendanceListAdapter.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileEditActivity.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageProfileViewHolder.kt
  core/common/src/main/java/com/mashup/core/common/extensions/StringExt.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/EditCell.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/MyProfileRepository.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/edit/MyPageEditProfileScreen.kt
Labels: UI, 기능

#467 Feature: 마이프로필 정보 저장 완료 했을 때 및 새로고침 했을 때 UI 처리 로직 개발
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileEditActivity.kt
  app/src/main/java/com/mashup/ui/mypage/viewholder/MyPageProfileViewHolder.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/MemberGenerationDao.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/MyProfileDao.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/data/dto/ValidResponse.kt
Labels: 기능
