Repository mash-up-kr/mashup_Android, pull requests merged in 2023-01, with the labels that each got.

#186 [Refactoring] QR Code GA Logging
  app/src/main/java/com/mashup/constant/UserActionLogs.kt
  app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
  app/src/main/java/com/mashup/ui/withdrawl/WithdrawalActivity.kt
Labels: 리팩토링

#193 [Feature] signup 화면에서 close, back ga 추가
  app/src/main/java/com/mashup/constant/log/UserActionKeys.kt
  app/src/main/java/com/mashup/constant/log/UserActionLogs.kt
  app/src/main/java/com/mashup/ui/login/LoginActivity.kt
  app/src/main/java/com/mashup/ui/qrscan/QRScanActivity.kt
  app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
  app/src/main/java/com/mashup/ui/signup/SignUpActivity.kt
  app/src/main/java/com/mashup/ui/withdrawl/WithdrawalActivity.kt
Labels: 기능

#175 [Feature] 설정화면 GA 적용
  app/src/main/java/com/mashup/constant/log/UserActionLogs.kt
  app/src/main/java/com/mashup/ui/setting/SettingActivity.kt
  app/src/main/java/com/mashup/ui/splash/SplashActivity.kt
  app/src/main/java/com/mashup/ui/withdrawl/WithdrawalActivity.kt
  app/src/main/java/com/mashup/util/AnalyticsManager.kt
Labels: 기능

#192 [ReFactoring] ButtonView Compose로 마이그레이션
  app/src/main/java/com/mashup/ui/widget/MashUpButton.kt
Labels: 리팩토링, UI

#190 [Feature] FCM 알람 표시하기
  app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt
Labels: 기능

#201 [Feature] FCM 알람에 이미지도 보여질 수 있도록 기능 추가
  app/src/main/java/com/mashup/util/MashUpFirebaseMessagingService.kt
Labels: UI, 기능

#202 [Feature] 푸시알림 수신 여부 설정하는 API 연결
  app/src/main/java/com/mashup/data/dto/PushNotificationRequest.kt
  app/src/main/java/com/mashup/data/repository/MemberRepository.kt
  app/src/main/java/com/mashup/network/dao/MemberDao.kt
  app/src/main/java/com/mashup/ui/setting/SettingViewModel.kt
Labels: 기능
