Repository mash-up-kr/mashup_Android, pull requests merged in 2024-06, with the labels that each got.

#493 [Fix] 스케쥴 위치 정보 관련 필드명 변경(address, placeName -> roadAddress, detailAddres…
  app/src/main/java/com/mashup/data/dto/ScheduleResponse.kt
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailAdapter.kt
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailViewModel.kt
  app/src/main/java/com/mashup/ui/schedule/detail/composable/ScheduleDetailLocationContent.kt
  app/src/main/java/com/mashup/ui/schedule/item/SchedeuleViewPagerInProgressItem.kt
  app/src/main/java/com/mashup/ui/schedule/item/ScheduleViewPagerSuccessItem.kt
  app/src/main/java/com/mashup/ui/schedule/model/EventDetail.kt
Labels: 리팩토링, UI

#501 기수 별 활동 카드를 수정할 때 무조건 가장 최신 기수의 정보를 물고 들어갔던 문제 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mashup/ui/attendance/member/MemberInfoDialog.kt
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileCardDetailActivity.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileCardEditActivity.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileEditActivity.kt
  app/src/main/java/com/mashup/ui/mypage/MyProfileMapper.kt
  app/src/main/res/layout/activity_my_profile_card_detail.xml
  app/src/main/res/values/strings.xml
  build.gradle
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/MyPageProfileEditViewModel.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/card/MyPageProfileCardScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/card/ProfileCard.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/card/ProfileCardDetailScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/edit/MyPageEditCardScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/edit/MyPageEditProfileScreen.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/model/LoadState.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/model/MyProfileCardEntity.kt
  feature/myPage/src/main/java/com/mashup/feature/mypage/profile/model/ProfileCardData.kt
Labels: 버그, 기능

#500 스케쥴 상세화면 리팩토링(디자인 수정 및 Compose 마이그레이션)
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailActivity.kt
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailAdapter.kt
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailScreen.kt
  app/src/main/java/com/mashup/ui/schedule/detail/ScheduleDetailViewModel.kt
  app/src/main/java/com/mashup/ui/schedule/detail/composable/ScheduleDetailContentItem.kt
  app/src/main/java/com/mashup/ui/schedule/detail/composable/ScheduleDetailHeaderItem.kt
  app/src/main/java/com/mashup/ui/schedule/detail/composable/ScheduleDetailInfoItem.kt
  app/src/main/java/com/mashup/ui/schedule/detail/composable/ScheduleDetailLocationItem.kt
  app/src/main/java/com/mashup/ui/schedule/detail/composable/ScheduleInfoText.kt
  app/src/main/java/com/mashup/ui/schedule/model/EventDetail.kt
  app/src/main/java/com/mashup/ui/schedule/model/EventDetailMapper.kt
  app/src/main/res/layout/activity_schedule_detail.xml
  app/src/main/res/layout/item_event_timeline_content.xml
  app/src/main/res/layout/item_event_timeline_header.xml
Labels: 리팩토링, UI

#506 스케쥴 화면에 Tab(이번 주 일정 / 전체 일정) 추가
  app/src/main/java/com/mashup/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/mashup/ui/schedule/ScheduleFragment.kt
  app/src/main/java/com/mashup/ui/schedule/ScheduleRoute.kt
  app/src/main/java/com/mashup/ui/schedule/ScheduleScreen.kt
  app/src/main/java/com/mashup/ui/schedule/component/ScheduleTabRow.kt
  app/src/main/res/values/strings.xml
  core/common/src/main/res/drawable/ic_more.xml
  core/ui/src/main/java/com/mashup/core/ui/widget/MashUpHtmlText.kt
Labels: UI, 기능

#504 empty 스케쥴 UI 구현
  app/src/main/java/com/mashup/ui/schedule/component/ScheduleTabRow.kt
  app/src/main/java/com/mashup/ui/schedule/item/EmptyScheduleItem.kt
  core/common/src/main/res/drawable/img_empty_schdule.png
  core/ui/src/main/java/com/mashup/core/ui/widget/MashUpButton.kt
  core/ui/src/main/java/com/mashup/core/ui/widget/MashUpGradientButton.kt
Labels: UI
